version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
python:
  install:
    - requirements: requirements/doc.txt
    - method: pip
      path: .
sphinx:
  builder: readthedocsdirhtml
  fail_on_warning: true